---
- name: 'Set a fact for whether this is a Debian-ish host.'
  ansible.builtin.set_fact:
    host_is_debian: "{{ ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' }}"

- name: 'Install Apt packages.'
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  when: host_is_debian
  loop:
    - 'git'
    - 'python3'
    - 'python3-pip'

- name: 'Install Pip packages.'
  become: yes
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - 'ansible'
